import { 
  Facility, 
  Vehicle, 
  AuditQuestion, 
  Supplier, 
  Announcement, 
  Operation,
  Profile 
} from "../supabase/types";

export const currentUser: Profile = {
  id: "user-001",
  email: "mehmet.yilmaz@idari360.com",
  full_name: "Mehmet Yılmaz",
  role: "facility_admin",
  phone: "0532 555 36 00",
  avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  is_active: true,
};

export const dashboardStats = {
  dateDisplay: "30 Mayıs 2026, Cuma",
  openDemands: {
    count: 12,
    subtext: "Toplam 32 talep",
  },
  inProgress: {
    count: 8,
    subtext: "Toplam 24 iş",
  },
  completed: {
    count: 216,
    subtext: "Bu ay",
  },
  pendingApprovals: {
    count: 5,
    subtext: "Onay bekleyen",
  },
  statusDistribution: [
    { name: "Yeni", value: 12, percentage: "37.5%", color: "#2563eb" },
    { name: "Devam Ediyor", value: 8, percentage: "25.0%", color: "#06b6d4" },
    { name: "Beklemede", value: 6, percentage: "18.8%", color: "#f59e0b" },
    { name: "Onayda", value: 3, percentage: "9.4%", color: "#8b5cf6" },
    { name: "Tamamlandı", value: 3, percentage: "9.4%", color: "#10b981" },
  ],
  monthlyTrend: [
    { month: "Oca", demands: 20 },
    { month: "Şub", demands: 38 },
    { month: "Mar", demands: 44 },
    { month: "Nis", demands: 36 },
    { month: "May", demands: 56 },
    { month: "Haz", demands: 68 },
  ],
  categoryRanking: [
    { name: "Yemekhane", count: 12, color: "#3b82f6" },
    { name: "Servis", count: 8, color: "#06b6d4" },
    { name: "Filo", count: 6, color: "#f59e0b" },
    { name: "Temizlik", count: 4, color: "#8b5cf6" },
    { name: "Diğer", count: 2, color: "#94a3b8" },
  ],
  satisfaction: {
    score: 4.6,
    maxScore: 5,
    title: "Yemekhane Memnuniyet Skoru",
    growth: "%8.2 artış (Geçen aya göre)",
  },
};

export const announcements: Announcement[] = [
  {
    id: "ann-1",
    title: "Bayram Tatili Duyurusu",
    content: "Kurban Bayramı tatili 6-9 Haziran tarihleri arasındadır. Nöbetçi personel listesi belirlenmiştir.",
    date: "30.05.2026",
  },
  {
    id: "ann-2",
    title: "Yemekhane Çalışma Saatleri",
    content: "1 Haziran itibarıyla yemekhane saatlerinde değişiklik olacaktır. Öğle servisi 12:00-14:00 saatleri arasındadır.",
    date: "28.05.2026",
  },
  {
    id: "ann-3",
    title: "Servis Güzergah Güncellemesi",
    content: "Bazı servis güzergahlarında güncelleme yapılmıştır. Yeni rota detaylarını Servis sekmesinden inceleyebilirsiniz.",
    date: "27.05.2026",
  },
];

export const facilitiesList: Facility[] = [
  {
    id: "fac-1",
    code: "SUB-001",
    name: "Agora Şubesi",
    city: "İzmir",
    address: "Mithatpaşa Cad. No:142 Balçova",
    phone: "0232 277 00 00",
    health_status: "good",
    satisfaction_score: 4.60,
    cleanliness_score: 92.5,
    pest_control_score: 96.0,
    waternet_score: 90.0,
    monthly_cost: 48500,
    is_active: true,
    created_at: "2024-01-15",
  },
  {
    id: "fac-2",
    code: "SUB-002",
    name: "Maslak Genel Merkez",
    city: "İstanbul",
    address: "Büyükdere Cad. No:245 Maslak",
    phone: "0212 335 00 00",
    health_status: "good",
    satisfaction_score: 4.85,
    cleanliness_score: 96.0,
    pest_control_score: 98.0,
    waternet_score: 94.0,
    monthly_cost: 112000,
    is_active: true,
    created_at: "2023-05-10",
  },
  {
    id: "fac-3",
    code: "SUB-003",
    name: "Kadıköy Lojistik Merkezi",
    city: "İstanbul",
    address: "E-5 Yan Yol No:12 Kozyatağı",
    phone: "0216 410 00 00",
    health_status: "warning",
    satisfaction_score: 3.90,
    cleanliness_score: 78.0,
    pest_control_score: 85.0,
    waternet_score: 79.0,
    monthly_cost: 64000,
    is_active: true,
    created_at: "2024-02-01",
  },
  {
    id: "fac-4",
    code: "SUB-004",
    name: "Bornova Depo & Dağıtım",
    city: "İzmir",
    address: "Sanayi Cad. No:88 Bornova",
    phone: "0232 461 00 00",
    health_status: "critical",
    satisfaction_score: 3.40,
    cleanliness_score: 68.0,
    pest_control_score: 72.0,
    waternet_score: 70.0,
    monthly_cost: 52000,
    is_active: true,
    created_at: "2023-11-20",
  },
  {
    id: "fac-5",
    code: "SUB-005",
    name: "Çankaya Tesisleri",
    city: "Ankara",
    address: "Turan Güneş Bulvarı No:60",
    phone: "0312 440 00 00",
    health_status: "good",
    satisfaction_score: 4.70,
    cleanliness_score: 94.0,
    pest_control_score: 95.0,
    waternet_score: 92.0,
    monthly_cost: 71500,
    is_active: true,
    created_at: "2024-03-05",
  },
];

export const vehiclesList: Vehicle[] = [
  {
    id: "veh-1",
    plate: "34 ABC 123",
    vehicle_type: "servis",
    brand: "Mercedes-Benz",
    model: "Sprinter 16+1",
    model_year: 2024,
    driver_name: "Ali Öztürk",
    driver_phone: "0532 999 11 22",
    driver_src_valid: true,
    driver_psychotechnic_valid: true,
    capacity: 16,
    passenger_count: 14,
    route_name: "Kadıköy - Maslak Ekspres",
    current_lat: 41.0125,
    current_lng: 28.9800,
    current_speed: 48.5,
    interior_temp: 22.4,
    ac_status: true,
    cleanliness_score: 94.0,
    status: "active",
    last_maintenance_date: "2026-04-10",
    next_inspection_date: "2026-10-15",
  },
  {
    id: "veh-2",
    plate: "34 XYZ 789",
    vehicle_type: "servis",
    brand: "Volkswagen",
    model: "Crafter 19+1",
    model_year: 2023,
    driver_name: "Kemal Aydın",
    driver_phone: "0533 777 44 11",
    driver_src_valid: true,
    driver_psychotechnic_valid: true,
    capacity: 19,
    passenger_count: 18,
    route_name: "Beylikdüzü - Maslak Ring",
    current_lat: 40.9980,
    current_lng: 28.9100,
    current_speed: 52.0,
    interior_temp: 23.1,
    ac_status: true,
    cleanliness_score: 91.0,
    status: "active",
    last_maintenance_date: "2026-03-22",
    next_inspection_date: "2026-09-20",
  },
  {
    id: "veh-3",
    plate: "35 IZM 360",
    vehicle_type: "servis",
    brand: "Ford",
    model: "Transit 16+1",
    model_year: 2025,
    driver_name: "Hüseyin Kaya",
    driver_phone: "0544 555 22 33",
    driver_src_valid: true,
    driver_psychotechnic_valid: true,
    capacity: 16,
    passenger_count: 15,
    route_name: "Bornova - Agora Ring",
    current_lat: 38.4192,
    current_lng: 27.1287,
    current_speed: 42.0,
    interior_temp: 21.8,
    ac_status: true,
    cleanliness_score: 96.0,
    status: "active",
    last_maintenance_date: "2026-05-02",
    next_inspection_date: "2026-11-05",
  },
  {
    id: "veh-4",
    plate: "06 ANK 360",
    vehicle_type: "filo",
    brand: "Renault",
    model: "Megane Sedan",
    model_year: 2024,
    driver_name: "İdari Saha Ekibi",
    driver_phone: "0312 440 00 00",
    driver_src_valid: true,
    driver_psychotechnic_valid: true,
    capacity: 5,
    passenger_count: 2,
    route_name: "Çankaya Saha Kontrol",
    current_lat: 39.9208,
    current_lng: 32.8541,
    current_speed: 35.0,
    interior_temp: 22.0,
    ac_status: true,
    cleanliness_score: 98.0,
    status: "active",
    last_maintenance_date: "2026-04-15",
    next_inspection_date: "2026-12-01",
  },
];

export const suppliersList: Supplier[] = [
  {
    id: "sup-1",
    name: "ABC Temizlik ve Tesis Hizmetleri",
    category: "Temizlik",
    contact_person: "Ahmet Demir",
    phone: "0532 111 22 33",
    email: "operasyon@abctemizlik.com",
    service_quality_score: 90.0,
    punctuality_score: 85.0,
    complaint_score: 82.0,
    staff_compliance_score: 95.0,
    audit_score: 86.0,
    action_closure_score: 84.0,
    overall_score: 87.0,
  },
  {
    id: "sup-2",
    name: "Lider Turizm Servis Taşımacılık",
    category: "Servis",
    contact_person: "Mustafa Kara",
    phone: "0542 333 44 55",
    email: "filo@liderturizm.com",
    service_quality_score: 92.0,
    punctuality_score: 94.0,
    complaint_score: 88.0,
    staff_compliance_score: 96.0,
    audit_score: 91.0,
    action_closure_score: 90.0,
    overall_score: 91.8,
  },
  {
    id: "sup-3",
    name: "Gourmet Catering & Yemek Sanayi",
    category: "Yemekhane",
    contact_person: "Ayşe Güler",
    phone: "0555 666 77 88",
    email: "kalite@gourmetcatering.com",
    service_quality_score: 88.0,
    punctuality_score: 90.0,
    complaint_score: 85.0,
    staff_compliance_score: 92.0,
    audit_score: 89.0,
    action_closure_score: 86.0,
    overall_score: 88.3,
  },
  {
    id: "sup-4",
    name: "Kale Güvenlik ve Koruma",
    category: "Güvenlik",
    contact_person: "Selim Yıldız",
    phone: "0533 888 99 00",
    email: "guvenlik@kaleguvenlik.com",
    service_quality_score: 95.0,
    punctuality_score: 96.0,
    complaint_score: 92.0,
    staff_compliance_score: 98.0,
    audit_score: 94.0,
    action_closure_score: 95.0,
    overall_score: 95.0,
  },
];

export const operationsList: Operation[] = [
  {
    id: "op-1",
    facility_id: "fac-1",
    operation_number: "TAL-2026-0012",
    title: "Agora Yemekhane İlave Saladbar Talebi",
    category: "yemekhane",
    description: "Yoğun öğle servisinde yetersiz kalan saladbar için ek ünite temini gerekmektedir.",
    priority: "orta",
    status: "yeni",
    deadline: "2026-06-05",
    created_at: "2026-05-30T09:15:00Z",
  },
  {
    id: "op-2",
    facility_id: "fac-1",
    operation_number: "TAL-2026-0011",
    title: "34 ABC 123 Nolu Servis Klima Bakımı",
    category: "servis",
    description: "Yolcu konforu için klima gazı dolumu ve filtre değişimi planlandı.",
    priority: "yuksek",
    status: "devam_ediyor",
    deadline: "2026-06-02",
    created_at: "2026-05-29T14:30:00Z",
  },
  {
    id: "op-3",
    facility_id: "fac-2",
    operation_number: "TAL-2026-0010",
    title: "Maslak Kat 3 Zemin Cila ve Derin Temizlik",
    category: "temizlik",
    description: "Hafta sonu mesai dışı saatte binicili makina ile yıkama ve cila işlemi.",
    priority: "orta",
    status: "onayda",
    deadline: "2026-06-03",
    created_at: "2026-05-28T11:00:00Z",
  },
  {
    id: "op-4",
    facility_id: "fac-3",
    operation_number: "TAL-2026-0009",
    title: "Kadıköy Depo Forklift Periyodik Kontrolü",
    category: "teknik",
    description: "Yıllık İSG mevzuat periyodik muayenesi tamamlandı, rapor bekleniyor.",
    priority: "acil",
    status: "tamamlandi",
    completed_at: "2026-05-29T16:00:00Z",
    created_at: "2026-05-25T10:00:00Z",
  },
];

// DENETİM SORULARI (Word & Excel tam dökümü)
export const serviceAuditQuestions: AuditQuestion[] = [
  { id: "sq-1", template_id: "tpl-servis", category_section: "Temizlik", question_text: "Aracın iç ve dış temizliği uygun mu?", points: 10, sort_order: 1 },
  { id: "sq-2", template_id: "tpl-servis", category_section: "Temizlik", question_text: "Araç içerisinde kötü koku, sigara kokusu veya hijyen sorunu var mı?", points: 10, sort_order: 2 },
  { id: "sq-3", template_id: "tpl-servis", category_section: "Müşteri Alanı", question_text: "Koltuklar sağlam, temiz ve yolcu kullanımına uygun mu?", points: 10, sort_order: 3 },
  { id: "sq-4", template_id: "tpl-servis", category_section: "Müşteri Alanı", question_text: "Klima sistemi çalışıyor ve yeterli performans gösteriyor mu?", points: 10, sort_order: 4 },
  { id: "sq-5", template_id: "tpl-servis", category_section: "İş Güvenliği", question_text: "Emniyet kemerleri tüm koltuklarda çalışır durumda mı?", points: 4, sort_order: 5 },
  { id: "sq-6", template_id: "tpl-servis", category_section: "İş Güvenliği", question_text: "Yangın söndürücü mevcut, dolum tarihi geçerli ve kolay ulaşılabilir mi?", points: 4, sort_order: 6 },
  { id: "sq-7", template_id: "tpl-servis", category_section: "İş Güvenliği", question_text: "İlk yardım çantası eksiksiz ve son kullanma tarihleri uygun mu?", points: 3, sort_order: 7 },
  { id: "sq-8", template_id: "tpl-servis", category_section: "İş Güvenliği", question_text: "Acil çıkışlar, acil çıkış çekici ve güvenlik ekipmanları çalışır durumda mı?", points: 3, sort_order: 8 },
  { id: "sq-9", template_id: "tpl-servis", category_section: "İş Güvenliği", question_text: "Lastiklerin diş derinliği ve genel durumu uygun mu?", points: 3, sort_order: 9 },
  { id: "sq-10", template_id: "tpl-servis", category_section: "İş Güvenliği", question_text: "Farlar, sinyaller, stop lambaları ve geri vites lambaları çalışıyor mu?", points: 3, sort_order: 10 },
  { id: "sq-11", template_id: "tpl-servis", category_section: "Evraklar", question_text: "Sürücü üzerinde kimlik kartı ve gerekli sürücü belgeleri (SRC, Psikoteknik vb.) güncel ve yanında mı?", points: 20, sort_order: 11 },
  { id: "sq-12", template_id: "tpl-servis", category_section: "Personel", question_text: "Sürücü personellere karşı saygılı ve profesyonel bir iletişim sergiliyor mu?", points: 20, sort_order: 12 },
];

export const foodAuditQuestions: AuditQuestion[] = [
  { id: "fq-1", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "El yıkama lavaboları fiziksel özellikleri uygun mu?", points: 2, sort_order: 1 },
  { id: "fq-2", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "El yıkama lavaboları ulaşılabilir, kullanıma uygun durumda mı?", points: 2, sort_order: 2 },
  { id: "fq-3", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "El yıkama dışında herhangi başka bir amaç için kullanılmıyor mu?", points: 2, sort_order: 3 },
  { id: "fq-4", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Üretim boyunca sıcak (ılık) su sağlanıyor mu?", points: 2, sort_order: 4 },
  { id: "fq-5", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "El yıkama talimatları mevcut mu?", points: 2, sort_order: 5 },
  { id: "fq-6", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Antibakteriyel sabun, el dezenfektanı, tek kullanımlık kağıt havlu temiz ve kullanılabilir durumda mı?", points: 2, sort_order: 6 },
  { id: "fq-7", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "El yıkama lavaboları yanında sadece pedallı çöp kovası mevcut mu?", points: 2, sort_order: 7 },
  { id: "fq-8", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Tüm personel gıda maddeleri ile temas etmeden önce ellerini yıkıyor mu?", points: 2, sort_order: 8 },
  { id: "fq-9", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Gerekli durumlarda talimatlara uygun eldiven kullanılıyor mu?", points: 2, sort_order: 9 },
  { id: "fq-10", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Sebze-Meyve Dezenfeksiyonu talimata uygun mu?", points: 2, sort_order: 10 },
  { id: "fq-11", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Tüm kritik limitler ile ilgili çalışanlar yeterli bilgiye sahip mi?", points: 2, sort_order: 11 },
  { id: "fq-12", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Gıda ürünlerinin tüm hazırlık aşamalarında çapraz kontaminasyona karşı önlem alınmış mı?", points: 2, sort_order: 12 },
  { id: "fq-13", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Ortamda üzeri açık gıda maddesi var mı?", points: 2, sort_order: 13 },
  { id: "fq-14", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Direkt yere bırakılmış ürün, ekipman vb. var mı?", points: 2, sort_order: 14 },
  { id: "fq-15", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Temiz ve kirli bölümler tanımlanmış mı?", points: 2, sort_order: 15 },
  { id: "fq-16", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Ürün grup ve risklerine göre renk koduna göre tezgah/bıçak ayrımı yapılmış mı?", points: 2, sort_order: 16 },
  { id: "fq-17", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Üretim alanında atık ve yabancı malzeme var mı?", points: 2, sort_order: 17 },
  { id: "fq-18", template_id: "tpl-yemek", category_section: "Hazırlık, Pişirme ve Sevkiyat", question_text: "Üretim alanında cam malzeme ve cam ambalaj var mı?", points: 2, sort_order: 18 },
  { id: "fq-19", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Servis personelinin kıyafeti, davranışları hijyen kurallarına uygun mu?", points: 2, sort_order: 19 },
  { id: "fq-20", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Servis bölümünün genel temizlik ve düzeni uygun mu?", points: 2, sort_order: 20 },
  { id: "fq-21", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Servis ekipmanları temiz mi?", points: 2, sort_order: 21 },
  { id: "fq-22", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Servis alanındaki tüm ekipmanlar kullanılabilir durumda mı?", points: 1, sort_order: 22 },
  { id: "fq-23", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Alanda alerjen afişleri mevcut mu?", points: 1, sort_order: 23 },
  { id: "fq-24", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Yemeklere yakın yerlerde besin etiketleri, alerjen besin tablosu mevcut mu?", points: 2, sort_order: 24 },
  { id: "fq-25", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Yemek salonu tertip ve düzeni talimatlara uygun mu?", points: 2, sort_order: 25 },
  { id: "fq-26", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Yemek salonu temiz ve düzenli mi? (masa, sandalye vb.)", points: 2, sort_order: 26 },
  { id: "fq-27", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Su sebilleri paslı değil ve temiz mi?", points: 2, sort_order: 27 },
  { id: "fq-28", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Saladbar, sos masaları, ekmek dolabı temiz ve düzenli mi?", points: 2, sort_order: 28 },
  { id: "fq-29", template_id: "tpl-yemek", category_section: "Servis Alanı ve Yemek Salonu", question_text: "Cam, yer, kalorifer petekleri, duvar temizliği uygun mu?", points: 2, sort_order: 29 },
  { id: "fq-30", template_id: "tpl-yemek", category_section: "Bina, Alet ve Ekipmanlar", question_text: "Alet ve Ekipmanlar uygun ve temiz mi?", points: 2, sort_order: 30 },
  { id: "fq-31", template_id: "tpl-yemek", category_section: "Bina, Alet ve Ekipmanlar", question_text: "Yer, raf, duvar, tavan, mazgal, dolap, kapı temizlikleri uygun mu?", points: 2, sort_order: 31 },
  { id: "fq-32", template_id: "tpl-yemek", category_section: "Sanitasyon", question_text: "Temizlik planları ve MSDS bilgileri mevcut mu?", points: 3, sort_order: 32 },
  { id: "fq-33", template_id: "tpl-yemek", category_section: "Sanitasyon", question_text: "Bulaşık makinasında son durulama suyu sıcaklığı 75°C ve üzerinde mi?", points: 3, sort_order: 33 },
  { id: "fq-34", template_id: "tpl-yemek", category_section: "Soyunma Odaları", question_text: "Soyunma odaları genel hijyen ve düzenleri uygun mu?", points: 2, sort_order: 34 },
];

export const cleaningAuditQuestions: AuditQuestion[] = [
  { id: "cq-1", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Streç ve karton atıkları toplanmış mı / toplanıyor mu?", points: 3, sort_order: 1 },
  { id: "cq-2", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Binicili makina ile yıkama yapılıyor mu?", points: 3, sort_order: 2 },
  { id: "cq-3", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Operasyon alanında yıkama araçlarına ait kullanma talimatları mevcut mu?", points: 3, sort_order: 3 },
  { id: "cq-4", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Operasyon alanında bulunan temizlik ekipmanları düzenli ve tanımlı yerlerde mi?", points: 2, sort_order: 4 },
  { id: "cq-5", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Temizlik ekipmanlarının fiziki ve temizlik şartları uygun mu?", points: 3, sort_order: 5 },
  { id: "cq-6", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Zeminlerde ve yüzeylerde toz, kir mevcut mu?", points: 3, sort_order: 6 },
  { id: "cq-7", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Rampa kapıları, kapı kumandaları ve aydınlatmalar temiz mi?", points: 3, sort_order: 7 },
  { id: "cq-8", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Spiraller ve sorter temiz mi?", points: 3, sort_order: 8 },
  { id: "cq-9", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Merdiven korkulukları temiz mi?", points: 3, sort_order: 9 },
  { id: "cq-10", template_id: "tpl-temizlik", category_section: "Operasyon Alanı", question_text: "Yüksek alan yangın boruları ve doğalgaz radyantları temiz mi?", points: 5, sort_order: 10 },
  { id: "cq-11", template_id: "tpl-temizlik", category_section: "WC ve Soyunma Odaları", question_text: "Temizlik talimatlarında tanımlanmış bez ve kimyasallar ile temizlik yapılıyor mu?", points: 3, sort_order: 11 },
  { id: "cq-12", template_id: "tpl-temizlik", category_section: "WC ve Soyunma Odaları", question_text: "Çöpler alınmış ve temiz mi?", points: 3, sort_order: 12 },
  { id: "cq-13", template_id: "tpl-temizlik", category_section: "WC ve Soyunma Odaları", question_text: "Tuvalet ekipmanları (sifon, sabun ve su armatürleri, kilit) çalışır durumda mı?", points: 3, sort_order: 13 },
  { id: "cq-14", template_id: "tpl-temizlik", category_section: "Ortak ve Mola Alanları", question_text: "Masalar ve oturaklar temiz mi?", points: 3, sort_order: 14 },
  { id: "cq-15", template_id: "tpl-temizlik", category_section: "Ortak ve Mola Alanları", question_text: "Çay alanı sarf malzeme tam, temiz ve çay demlenmiş mi?", points: 6, sort_order: 15 },
  { id: "cq-16", template_id: "tpl-temizlik", category_section: "Ofis Alanları", question_text: "Ofis mutfak alanı ve zeminler temiz mi?", points: 6, sort_order: 16 },
  { id: "cq-17", template_id: "tpl-temizlik", category_section: "Ofis Alanları", question_text: "Toplantı odaları camları ve masalar temiz mi?", points: 6, sort_order: 17 },
  { id: "cq-18", template_id: "tpl-temizlik", category_section: "Ofis Alanları", question_text: "Ofis WC'ler temiz ve düzenli mi?", points: 6, sort_order: 18 },
];
